### PR TITLE
Test Case: Issue 3139

### PR DESCRIPTION
**Pull request by dbakaev**
Added coverage for issue 3139, review, please #3139

### CODE REVIEW

**Comment by pavelciapa** [comment]
Changed fonts differs from machine to machine; need to investigate appropriate font

**Comment by pavelciapa** [comment]
The last step - 
`7 | Go to this site. | All the changes made can be seen.`

@tracywalker  can we specify in test description that we need to see that fonts are different from that were at start? ss custom fonts are different on different machines, despite the font name is the same. 

- If so, should we have another test to check that specific font is applied?

**Comment by tracywalker** [comment]
> The last step -
> `7 | Go to this site. | All the changes made can be seen.`
> 
> @tracywalker can we specify in test description that we need to see that fonts are different from that were at start? ss custom fonts are different on different machines, despite the font name is the same.
> 
>     * If so, should we have another test to check that specific font is applied?

The intent of the test is to check that changing font and font size does indeed apply to web page.  You can probably do this reliably by changing the font style and size dramatically.

**Comment by pavelciapa** [comment]
> You can probably do this reliably by changing the font style and size dramatically.

We tried to check a certain pattern for changed font. But now we will check that default pattern is no longer on the page after changing a font

**Pull request merged**
