### PR TITLE
Fix image_rich_scrolling: Issue 3761

### PR DESCRIPTION
**Pull request by pavelciapa**
Added coverage for #3761

### CODE REVIEW

**Comment by pavelciapa** [comment]
> Instead of commenting out the blocked_by, remove the blocked_by statement.
> 
> image_site_(next)_loaded.png are too generic, please use something like pixbay_site_loaded.png

- removed comment
- renamed pattern

**Comment by tracywalker** [comment]
The test loads up new page, but doesn't appear to do any scrolling.  It just closes the browser and Iris thinks test passed.

**Comment by pavelciapa** [comment]
> The test loads up new page, but doesn't appear to do any scrolling. It just closes the browser and Iris thinks test passed.
> 
> Not approved.

Added timeout to wait until image content is loaded.

**Comment by tracywalker** [comment]
Paul, this didn't get landed, please review it and land if it is still ok.

**Comment by paulprokhorovmoz** [comment]
@tracywalker  There is no need to land this - it successfully works from dev branch. We filed this issue before using VPN approach to avoid captcha.

**Comment by tracywalker** [comment]
Yes, however, whenever we can avoid using Google search we should. In this case, we can use another source for an image rich page.  Please fix the test/branch so it can be merged to dev.  Thank you.

**Pull request merged**
