### PR TITLE
Fix: 4577_new_bookmark_dialog_window_save_keyword

### LINKED ISSUE #4577: Fix new_bookmark_dialog_window_save_keyword
The test script failed in OSX.

Error: AssertionError
Message: The keyword search displays as first suggestion the bookmarked website.

### PR DESCRIPTION
**Pull request by ranjit-exalt**
Applying this patch will fix #4577.

### CODE REVIEW

**Review by spronoza — CHANGES_REQUESTED** [review]
Failing on OSX
[20200122183812.zip](https://github.com/mozilla/iris_firefox/files/4098512/20200122183812.zip)

**Comment by ranjit-exalt** [comment]
> Failing on OSX
> [20200122183812.zip](https://github.com/mozilla/iris_firefox/files/4098512/20200122183812.zip)

To handle Mac failure in some machine, done the following changes:
1. Click on name_bookmark_field to ensure that the cursor is on the first field.
2. Two tab click is working fine on my mac but from PR (#4592)debug image it looks like the cursor is skipping next field. So, replaced the TAB key with the DOWN key. Pressing down key on tags drop down to take it to the next field(keywords).
3. Replaced name_bookmark_field.png for MAC.

Replaced auxiliary_window_close_button for windows 7.

**Review by spronoza — APPROVED** [review]
Approved

**Review by paulprokhorovmoz — APPROVED** [review]
Code review is completed.

**Pull request merged**
