### PR TITLE
Issue 4271: Issues fixed for download_manager test suit

### PR DESCRIPTION
**Pull request by ranjit-exalt**
Failed test cases for download_manager (#4271)  test suit have been fixed, for all four operating systems. 

Updated run report for all four OS are as follows: 

###  Mac: 
**Passed: 24, Failed: 0, Skipped: 5, Errors 0**  -- Total: 29

###  Win 10: 
**Passed: 24, Failed: 0, Skipped: 5, Errors 0**  -- Total: 29

###  Win 7: 
**Passed: 24, Failed: 0, Skipped: 5, Errors 0**  -- Total: 29

###  Linux: 
**Passed: 22, Failed: 0, Skipped: 7, Errors 0**  -- Total: 29                                                                                                                                                                                  

There are few blocked test cases yet to fix. It will be fixed based on test case priority. Please review and merge the code.

### CODE REVIEW

**Comment by ranjit-exalt** [comment]
All four test cases marked fail in Mac, are working fine at my end (Mac 10.14.6; 1440x900; non-retina). Run screenshot attached below: 

image

I have requested @tracywalker to run at his end so that failure root cause can be investigated further.

**Comment by tracywalker** [comment]
I am testing on OSX 10.13  In your working branch, the only test, of those four, that fails for me is uncommon_warning.py in the assert at lines 55-56.  The debug image shows the lengthy pattern of text on screen.  It is probably fixable with a similarity adjustment.

**Comment by ranjit-exalt** [comment]
Fixed Mac issue for "uncommon_warning.py".

For Linux, all tests passed at my end, in a single run. 

Linux run for failed test cases


After carefully analyzing the run reports shared by Paul, It seems, the Linux system where tests were executed, was very slow (It took more than an hour to execute 22 test cases, as per shared test log). 

Out of 5 failed test cases, 1 failed due to firefox couldn't launch. And, rest 4 failed after identifying that the image exists, but unable to click due to excessive system slowness. I have given adequate wait time for clicks as well.

To avoid test failure at normal system slowness, fixed at a couple of places. Please test this at some other Linux system which is not heavily slow. Let me know if any other fixes required.

**Comment by paulprokhorovmoz** [comment]
@tracywalker  Please check these tests, they are still failing on our VM:
 - download_warnings_customized_or_disabled_from_the_ui.py
 - malicious_warning.py
 - potentially_unwanted_app.py
 - uncommon_warning.py

**Comment by tracywalker** [comment]
I checked those Monday.  The only failure I observed was uncommon_warning.py,  as posted above.  Ranjit says he has addressed this.

What platform are you seeing this continue to fail on?

**Comment by ranjit-exalt** [comment]
> What platform are you seeing this continue to fail on?

This is for Linux.

**Comment by paulprokhorovmoz** [comment]
No, I meant OSX

**Comment by tracywalker** [comment]
Those tests pass for me on Linux as well.

**Pull request merged**
