### PR TITLE
Issue 3904: New Test Case

### PR DESCRIPTION
**Pull request by ranjit-exalt**
Scripting completed for issue: https://github.com/mozilla/iris_firefox/issues/3904

Please review and merge.

### CODE REVIEW

**Review by paulprokhorovmoz — CHANGES_REQUESTED** [review]
This test should be implemented only for Linux, as it written in description.

**Comment by tracywalker** [comment]
> This test should be implemented only for Linux, as it written in description.

No, this should be implemented on all platforms.  The test name in TestRail was derived form the bug in Firefox (which apparently only affected Linux at the time of the bug report).  The functionality of DnD tabs should be tested on all platforms.

**Comment by paulprokhorovmoz** [comment]
Fails on Linux, see attachment
[20191227151015.zip](https://github.com/mozilla/iris_firefox/files/4005363/20191227151015.zip)

**Comment by ranjit-exalt** [comment]
> Fails on Linux, see attachment
> [20191227151015.zip](https://github.com/mozilla/iris_firefox/files/4005363/20191227151015.zip)

Reduced drag and drop speed to handle test failure on slower machines. Please review and do the needful.

**Comment by ranjit-exalt** [comment]
Conflicts resolved. Please review @paulprokhorovmoz

**Comment by paulprokhorovmoz** [comment]
@ranjit-exalt  Replace the **new_tab_image_pattern** variable value for all platforms because it corresponds to a part of inactive tab image, that is why it constantly fails on the  `assert new_tab_image, "Could not open new window"` step

**Comment by ranjit-exalt** [comment]
> @ranjit-exalt Replace the **new_tab_image_pattern** variable value for all platforms because it corresponds to a part of inactive tab image, that is why it constantly fails on the `assert new_tab_image, "Could not open new window"` step

@paulprokhorovmoz : The issue has been handled. Please review.

**Comment by paulprokhorovmoz** [comment]
Fails under Linux, see attachment
[issue_3904_linux_fails.zip](https://github.com/mozilla/iris_firefox/files/4070602/issue_3904_linux_fails.zip)

**Comment by ranjit-exalt** [comment]
> Fails under Linux, see attachment
> [issue_3904_linux_fails.zip](https://github.com/mozilla/iris_firefox/files/4070602/issue_3904_linux_fails.zip)

It's working fine at our end but by looking at debug images, fixed possible failure reason. Please review and retest.

**Review by spronoza — CHANGES_REQUESTED** [review]
Failing on Linux
image

**Comment by ranjit-exalt** [comment]
> Failing on Linux
> image

Please review.

**Pull request closed without merging**
