### PR TITLE
Fix data_after_restart test 

### PR DESCRIPTION
**Pull request by spronoza**
Fix data_after_restart test #3454

### CODE REVIEW

**Comment by pavelciapa** [comment]
Despite twitter is loaded, it doesn't appear in history. Timeout after loading twitter doesn't help.

Fails on **line 167** when checking twitter logo on all platforms.

@tracywalker is this a bug?

image

image

**Comment by tracywalker** [comment]
Yes, that looks like a bug in Firefox.

**Comment by spronoza** [comment]
The same behavior found in the #3455  data_after_shutdown also. Can you please file a bug on Bugzilla, @pavelciapa

**Comment by pavelciapa** [comment]
Filed a bug on Bugzilla

**Comment by tracywalker** [comment]
Block the testcase for now. Then, please ask the test author if this test depends on Twitter, or can we use a locale test page instead.

**Pull request merged**
