### PR TITLE
Issue 3125: Firefox Home Content - Highlights can be displayed in 1 or 2 rows

### PR DESCRIPTION
**Pull request by ranjit-exalt**
Issue https://github.com/mozilla/iris_firefox/issues/3125: Firefox Home Content - Highlights can be displayed in 1 or 2 rows

Test case scripted and tested for all four operating systems.

### CODE REVIEW

**Comment by paulprokhorovmoz** [comment]
- Rewrite assertions to make it possible to investigate what pattern isn't displayed in case of failure.
- Test doesn't check that highlighted items are in row, you just check they are displayed.

**Comment by ranjit-exalt** [comment]
> * Rewrite assertions to make it possible to investigate which pattern isn't displayed in case of failure.
> * Test doesn't check that highlighted items are in row, you just check they are displayed.

- Assert error messages modified for better investigation, in case of failure. Now when AssertionError occurs, it will display the exact image name.

- To handle the following 6 scenarios, six new regions have been implemented: 

  1. There are 4 cells displayed in a row. 
  2. If the browser is resized, the cells will be arranged as 3 cells in one row. 
  3.  If the browser is further resized, ultimately the cells will be arranged as 3 cells in 2 rows.
  4. There are 8 cells displayed in 2 rows. 
  5. If the browser is resized, the cells will be arranged as 6 cells in one row, 
  6.  If the browser is further resized, ultimately the cells will be arranged as 6 cells in 3 rows.

- Added DEFAULT_MOVE_MOUSE_DELAY after a click instance.

**Comment by ranjit-exalt** [comment]
> You still don't check that required patterns are in the row. You could perform this, for example, by comparing the coordinates of patterns.

@paulprokhorovmoz : It has been already validated by a region creation i.e. region_creation_highlights().   Let me explain you with an example for Non-retina Mac (1440x900): 

To validate whether 4 highlight items are in a row or not, I have created a region where it will first calculate the size and coordinate of text padding of first highlight cell which is approx: 205x40 and If you calculate one row with 4 cells, the required size will be 1006x160.  
So for 4 highlights cell the region is getting created like: 
highlights_region = Region(
            highlights_option_1st_cell_location.x - highlights_cell_width / 2,
            highlights_option_1st_cell_location.y - highlights_cell_height * 3.25,
            highlights_cell_width * 5.5,
            highlights_cell_height * 4.5,
        )

If you put the calculation here, you will see I am creating a region with size 1127.5x180. The extra height and width have been added for margins as I am shifting x and y coordinate by 100 and 12 pixels. You can see the below-attached region image captured in my debugger, it is clearly showing only 4 cells: 

image

In the same way, all the regions are being created. To see all the regions, please add time.sleep(2) before region return (at line 278) so that the region's screenshots can be captured in debug images. 

**No code change required.**

**Comment by paulprokhorovmoz** [comment]
Code review is completed.

**Pull request merged**
