### PR TITLE
Issue 4213: Fix failing search_and_update test cases for Linux in FxBeta71

### PR DESCRIPTION
**Pull request by ranjit-exalt**
Linux issues fixed for following 8 test cases: 

1. keyboard_shortcuts_work_in_search_bar.py
2. change_the_default_search_engine.py
3. middle_clicking_search_results_open_new_tab.py
4. one_off_search_engines_can_be_removed_and_restored.py
5. remove_search_engine.py
6. search_bar_submission_with_no_input.py
7. search_suggestions_are_displayed_in_search_bar.py
8. search_with_search_engines_keywords.py

Following two test cases are still failing due to existing pending issues: 
1. **default_search_code_yandex.py**: Failing due to the captcha issue. There is an issue logged by Tracy for this. https://github.com/mozilla/iris_firefox/issues/4010. No fix required. 
2. **search_suggestions_can_be_disabled.p**y: Fixed similarity failure issue. But It is still failing as there is no "Show suggestions" option in the search bar context menu in 71.011 build. There is an issue already raised by "Serhii Pronoza". https://github.com/mozilla/iris_firefox/issues/2739#event-2749156200"

### CODE REVIEW

**Comment by spronoza** [comment]
Here is the updated steps. You can update search_suggestions_can_be_disabled according to it.
https://testrail.stage.mozaws.net/index.php?/cases/view/4273

**Comment by ranjit-exalt** [comment]
> Here is the updated steps. You can update search_suggestions_can_be_disabled according to it.
> https://testrail.stage.mozaws.net/index.php?/cases/view/4273

Test case modified as per test steps given in test rail. Test Pass for Linux. A separate commit will be created for the other 3 operating systems (Win 10, Win 7 and Mac).

**Comment by paulprokhorovmoz** [comment]
Resolve conflicts.

**Comment by ranjit-exalt** [comment]
> Resolve conflicts.

Conflict resolved by replacing the "search_bar_magnifying_glass.png" image. This conflict was arose due to changes done by @spronoza. We both changed the same image. I have accepted my change as the image uploaded by me is a little more precise as it has no border. It should work for Serhii as well.

**Comment by ranjit-exalt** [comment]
Final commit done for Test case "search_suggestions_can_be_disabled" for all the operating systems.  @paulprokhorovmoz : Please review.

**Pull request merged**
