### PR TITLE
Issue 3115

### PR DESCRIPTION
**Pull request by ranjit-exalt**
Test case review for Issue_3115: "**Firefox Home Content - Firefox can select which Highlights to display**"

### CODE REVIEW

**Comment by ranjit-exalt** [comment]
Please find below the code changes details/remark for each review comments: 

> Replace wait calls by exists where necessary.

Most of the wait call has been replaced by exists. There are two wait functions that are still there which are required as per program need. 

> Remove unnecessary time.sleep() calls

Removed all the time.sleep(), apart from one at line no 128 where save window needs some time lag to appear on browser. 

> Change empty exception handling statement at line 153.

For download page verification, if during the first run test case fail after downloading the page, it will retry. During retry, when the system tries to download the same page again, for Mac and Linux one additional pop will appear. To handle that pop-up, this try-except is written. Since this is an optional popup, exception handling is not required. I have added a remark in the empty exception section for the reference. 

> Fix typos in log messages.

Checked typo in current log and error messages.

**Comment by paulprokhorovmoz** [comment]
- Replace code at lines 123-126 with the open_save_page() shortcut function

> For download page verification, if during the first run test case fail after downloading the page, it will retry. During retry, when the system tries to download the same page again, for Mac and Linux one additional pop will appear. To handle that pop-up, this try-except is written. Since this is an optional popup, exception handling is not required. I have added a remark in the empty exception section for the reference.
- I don't see any reason to use wait instead of exists in this case, just investigate how the exists function works

**Comment by ranjit-exalt** [comment]
> * Replace code at lines 123-126 with the open_save_page() shortcut function
> 
> > For download page verification, if during the first run test case fail after downloading the page, it will retry. During retry, when the system tries to download the same page again, for Mac and Linux one additional pop will appear. To handle that pop-up, this try-except is written. Since this is an optional popup, exception handling is not required. I have added a remark in the empty exception section for the reference.
> 
> * I don't see any reason to use wait instead of exists in this case, just investigate how the exists function works

**Both the suggested changes done. Summary of change:**

1. open_save_page() function replaced the following code written at lines 123-126

        if OSHelper.is_mac():
            type(text='s', modifier=KeyModifier.CMD)
        else:
            type(text='s', modifier=KeyModifier.CTRL)

2. try-except block with empty exception removed by exists-if statement. Change summary: 
**old:** 

        if OSHelper.is_mac() or OSHelper.is_linux():
            try:
                wait(replace_button_duplicate_check)
                click(replace_button_duplicate_check)
            except FindError:
                # No exception handling needed here as replace button only appear in case of duplicate download
                # If the replace button doesn't appear, it means first-time download, hence proceed to next step
                pass

**New:**

        if OSHelper.is_mac() or OSHelper.is_linux():
            replace_button_duplicate_check_exists = exists(replace_button_duplicate_check,
                                                           FirefoxSettings.FIREFOX_TIMEOUT)
        if replace_button_duplicate_check_exists:
            click(replace_button_duplicate_check)

**Comment by paulprokhorovmoz** [comment]
- Replace code at lines 99-104 with the exists function.
- Change PNG extensions to png for images.

**Comment by ranjit-exalt** [comment]
> * Replace code at lines 99-104 with the exists function.
> * Change PNG extensions to png for images.

Replaced code at lines 99-104 with the exists function.

Changed .PNG extension with .png but since file name is same, and .PNG and .png has no logical difference, git is recognizing both as same file. Hence not recognizing in git commit. In test cases, these images have been already used as .png

**Comment by paulprokhorovmoz** [comment]
Fails under Win 7:
3115_win7_fail_14_11_1
[3115_win7_debug_images.zip](https://github.com/mozilla/iris_firefox/files/3846656/3115_win7_debug_images.zip)

**Comment by ranjit-exalt** [comment]
> Fails under Win 7:
> 3115_win7_fail_14_11_1
> [3115_win7_debug_images.zip](https://github.com/mozilla/iris_firefox/files/3846656/3115_win7_debug_images.zip)

Issue fixed. It was failing due to the time lag for a download page to appear in the highlights section.  To handle this, the download page pre-requisite shifted at the beginning of the test case. Please test.

**Comment by paulprokhorovmoz** [comment]
Code review is completed.

**Pull request merged**
